# Permalinks
permalink:        pretty

# Setup
title: 'Universal Ctags'
tagline: 'A maintained ctags implementation'
description: 'A maintained ctags implementation'
url: 'https://ctags.io'

paginate: 5
paginate_path: "/blog/page:num/"

version: 0.1.0

github:
  repo: https://github.com/universal-ctags/ctags
